#!/usr/bin/env bash

exec >~/.logs/xsession 2>&1
export LANG="en_GB.UTF-8"
export LANGUAGE="en_GB.UTF-8"
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
export _JAVA_AWT_WM_NONREPARENTING=1
wmname exwm
xset -dpms
xset s off
# xss-lock -- gnome-screensaver-command -l &
xhost +SI:localuser:$USER

# Set default cursor.
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate.
xset r rate 200 60

# Uncomment the following block to use the exwm-xim module.
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim

xsettingsd &
picom -b --experimental-backends --dbus &
~/.fehbg &
exec emacs -mm --with-exwm --debug-init
