#!/usr/bin/env bash

RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"

DIR="/home/ebeem/.wallpapers"
HOUR=$(($(date +%k)))
STYLE=$(sed -nr "/^\[wallpaper\]/ { :l /^name[ ]*=/ { s/.*=[ ]*//; p; q;}; n; b l;}" ~/.config/dynamic-wallpaper/dwall.conf)

IMAGE="$DIR/$STYLE/$HOUR"

# get image format
if [[ -f "${IMAGE}.png" ]]; then
    FORMAT="png"
elif [[ -f "${IMAGE}.jpg" ]]; then
    FORMAT="jpg"
else
    echo -e ${RED}"[!] Invalid image file $IMAGE, Exiting..."
    exit 1;
fi

feh --bg-fill "$IMAGE.$FORMAT"
